### PR TITLE
Limit group and organization visibility to admins only

### PR DESCRIPTION
**Pull request by Razorfang**
Allow only admins of groups and organizations to view those groups or organizations.

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Hi @Razorfang ,

Thanks for the PR.

I see you've implemented filtering for the list of Organisations - good use of the filtering available in Grails.

However, the task asked for something slightly different:
*  it should not show the list of Administrators at the Org and Group detail - you should see the list of administrators for an Org or a Group only if you are an administrator yourself.
*  hide the list of Groups from users who are not Administrators at the Organisation level - similar protection to how list of Accounts is protected.

I think there might have been a misunderstanding of the task - that also manifested itself in me not getting your explanation for the need to use the filtering.

The list of Organisations on the VHO is not something that really asks to be hidden  (list of Organisations in Tuakiri is public), though users with no admin rights have no specific need to see the organisation.

However, there is still access that the app permits and should be blocked:
* Directly accessing an organisation via a "guessed" link - e.g., https://jgetty-test.reannz.co.nz/organisations/groups/show/30
* This link still shows the admins even if the user is not an admin of the organisation.
* This could be solved by either blocking access (if deciding users should not see organisations), or adjusting the visibility of admins the same way as visibility of accounts is done.
* And similar filtering for the list of groups.
* The access controls for the view of an organisation will have to also deal with the case when the user is an admin only in a group.
    * I'm not sure which way to go about seeing other parts of the organisation:
    * An admin of a group could (perhaps should) see admins of the organisation.
    * Should definitely see admins and accounts of his own group.
    * Should not have access to other groups of the organisation.
    * Not sure how to go about seeing presence of other groups.

There is perhaps some discussion to be had, and code will have to deal with access to details of organisations and groups - and likely with the details shown there.

Talk to you tomorrow in the office.

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Hi @Razorfang , as just discussed, let's solve it with the following rules:

1. A user with no admin privileges (no org, no group admin) will not see any groups or organisations.
2. A user with admin privileges over either an entire organisation or a group within that organisation will be considered an "insider" for the organisation and should be able to see everything for the organisation as has been up to now: details of the org, list of admins, list of group admins.  (Even for other groups then were the user is an admin, in case the user is just a group admin).
3. This will have to be enforced not just when rendering the list of organisations, but also in the controller when accessing an organisation directly by a URL/id.

I hope this covers all cases - anything unclear, please just ask.

Cheers,
Vlad

**Comment by Razorfang** [comment]
@vladimir-mencl-eresearch  Can you describe the issue you found today?

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, just tested and:
1. a user with just admin rights over a Group but not the containing Organisation could not access the organisation:
    * not shown on Organisation list
    * when navigating from the group to the Organisation, got a 500
2. For any access that should have been denied, I was getting a 500 - should be handled gracefully.

Cheers,
Vlad

**Comment by Razorfang** [comment]
@vladimir-mencl-eresearch  New changes are available to test.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks!  Just testing (as a user with access to only a single group and no org).

* I still cannot access the organisation the group belongs to and get a 500 error page.
* I also get the 500 error page for any other organisation I don't have access to.

However, when attempting to access a Group I don't have access to, I get *correctly* redirected to the list of groups itself - great to see this.

* Note that after the redirect to list of groups, I get a flash `Error` message with just label ID ` controllers.aaf.vhr.organization.show.error `.  I assume this is a placeholder that will still be populated in the message catalogue - and btw, it looks like this message ID is for an `Organisation`, so Groups will possible use a different message  ID with a slightly different wording of the message?

Please let me know once these are resolved and it's ready to test again.

Cheers,
Vlad

**Comment by Razorfang** [comment]
I think there was a typo in one of the checks. Pushing a change now.

**Comment by Razorfang** [comment]
Changes will be up soon

**Comment by Razorfang** [comment]
@vladimir-mencl-eresearch  Try now

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, testing now.

* Good to see that inaccessible organisations / groups now correctly redirect to the index page - and the error message is now showing expanded too.

* However, the index of organisations is missing the organisations where the user is only a Group admin (even though the user is correctly allowed to see the details of the organisation when navigating there from the group).

* And the restrictions for Groups are too tight: being an Organisation admin implies being an admin over  all Groups of the Organisation, but a user who is an Org admin currently cannot access the Groups of that organisation (nor see them in the global list of groups).

Cheers,
Vlad

**Comment by Razorfang** [comment]
I will address these tomorrow.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @Razorfang ,

I've just had a  look (testing against deployment at your host) and when testing with a user who is just an admin of a group:
* While I can access the organisation from the group itself, I cannot see the organisation listed in the list of organisations
* When I try accessing another group within the same organisation (as per above, user who is an admin of at least one group is an "insider" to the organisation), I get redirected to the group list instead 
* and then I get a 500 error on the group list.

Can you please check?

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
And when accessing as a user with admin rights over an Organisation, I also get the 500 on the group list.

When accessing as a user with admin rights over an Organisation AND a group within the organisation, I get a 500 on the list of Organisaitons.

**Comment by Razorfang** [comment]
Alright, I've decided to be more thorough with my testing since we're going back and forth a lot. I should be more diligent.

Here are the tests cases that I will check off:

- [x] AAF administrator is able to view and access all groups and organizations.
- [x] If you are an administrator of an organization, you can see that organization in the list.
- [x]  If you are an administrator of an organization, you can see that organization-specific page.
- [x] If you are not an administrator of an organization, but you are an administrator of a group within that organization, you can see that organization in the list.
- [x] If you are not an administrator of an organization, but you are an administrator of a group within that organization, you can see that organization-specific page.
- [x] If you are neither an administrator of an organization, nor an administrator of any group within that organization, you cannot see that organization in the list.
- [x] If you are neither an administrator of an organization, nor an administrator of any group within that organization, you cannot see that organization-specific page.
- [x] If you are an administrator of a group, you can see that group in the list.
- [x]  If you are an administrator of a group, you can see that group-specific page.
- [x] If you are an administrator of a group, you can see any organization the group is a part of in the list.
- [x] If you are an administrator of a group, you can see the specific page of any organization the group is a part of.
- [x] If you are not an administrator of a group, you cannot see that group in the list.
- [x] If you are not an administrator of a group, you cannot see that group-specific page.

**Comment by Razorfang** [comment]
@vladimir-mencl-eresearch  Try now, or whenever you're feeling up to it

**Comment by vladimir-mencl-eresearch** [comment]
Hi @Razorfang , looking at this now.

Good idea to write up all the specific cases - thanks for that, will help to avoid confusion.

It mostly aligns with the high-level description I gave above, with some minor differences:
* points 10, 11 in your list are worded as if a Group could belong to multiple Organisations - it always belongs only to one Organisation.  But that does not have any material impact, just noting it to avoid confusion.
* The last two points differ from my outline above, where I defined the concept of a user being an "insider to an  organisation" (admin of the org or any group within the org), and listed it that such user would be able to see any groups within the organisation:
> A user with admin privileges over either an entire organisation or a group within that organisation will be considered an "insider" for the organisation and should be able to see everything for the organisation as has been up to now: details of the org, list of admins, list of group admins. (Even for other groups then were the user is an admin, in case the user is just a group admin).
* I would not expect security harm from users who already have some admin rights there, and within a single organisation, it would lead to a more consistent experience.  Right now, while such user can see the list of groups on the org details page (finding that other groups exist), they cannot navigate to the other groups.

It would also be possible to add filtering to the org details page and go the more restrictive path (hiding other groups from users who are groups admin only), I think the concept of "organisation insiders" would lead to cleaner model with less surprises.   You could implement it as a helper function (? `userAdminWithinOrg` ?) that could be reused at the various decision and code points.


I have now also tested the deployed code:

* When a user is both an administrator of an organisation and of a group in the organisation, the group gets listed twice on the list
* And the difference in the expectations in what happens for users who are admins of only a group with respect to other groups.


Thanks for the patience with this, we are getting there.

Please wait for me to also review the source code - I have so far only tested the behaviour of what's deployed, have not seen the code yet, was waiting until we fix the runtime behaviour.

I should be able to come online also once in the afternoon once we get code behaviour into the right shape.

Cheers,
Vlad

**Comment by Razorfang** [comment]
@vladimir-mencl-eresearch  All concerns should be addressed now. The changes are live.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @Razorfang ,

Just testing now - with an account that has admin over only a single group (`Tuakiri Default`).

(1) When testing with an account that has Group Admin only and try to access the details of the group's Organisation, I (again)  get a 500 page.

(2) When attempting to access a different group in the same organisation, I get redirected to the group list and (2b) the list does not contain the group.  See previous post above.

(3) When testing with an account with Organisational Admin privileges, on the Groups List page ( `/groups/list` ), I only get to see groups I'm *explicitly* admin of, not through the Organisation.

Thanks for looking into these.

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Thanks @Razorfang , "almost there".

I only see an odd issue at `/groups/list`: groups of an Organisation get listed only when the user is explicitly an administrator for at least one group of the Organisation.  When the user is only directly an administrator of the Organisation but not explicitly of any group, the `/groups/list` page renders an empty list.

**Comment by Razorfang** [comment]
I'll check it out

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, retested now and behaviour matches up.  I'll get to reviewing the code changes now.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Jamie,

Thanks for all the effort put into this.  I see the code now does what it should, I'm now reviewing it for clarity / readability / understandability - so that it makes sense to someone coming to it in a few years' time.

(1) At the high level, the concept of the "org insider" is "user is admin of the org itself or any group".

The `isOrganizationInsider` and `getInsiderGroups` methods should actually implement this concept - right now, they skip over the case where the user is administrator of an organisation directly.  By adjusting the methods to match the concept (i.e., return true also when the user is admin of the org itself / include groups from Organisations where the user is an admin directly), we might simplify other code quite a bit:

(2) `OrganizationController.show`: the sequence of `if`s could fold to a single condition "isGlobalAdmin OR isOrgInsider"

(3) and the same for ` GroupController.show`: again, sequence of `if`s  could fold to a single condition "isGlobalAdmin OR isOrgInsider"

(4) `GroupController.list` would not have to pull in `getAdminOrgs`

Now minor things:
(5) `getAdminOrganisations()` is duplicated between `OrganizationController` and `AdminHelper`

(6) `virtualhome/grails-app/views/organization/show.gsp`: we are in the end not changing the visible groups of an Org, so can stick to original code here - no need to pass `visibleGroups`

(7) `DashboardController`: I'd drop the change there: even if the user can see the Orgs from the list, we can leave the Dashboard shortcuts only for Orgs/Groups they're directly an admin of.

And a few nits:
* AdminHelper is missing final EOL
* errmsg: " is forbidden from accessing" => " does not have permissions to access"
  (forbidden suggests explicit ban, here it's just lack of permissions)
* VHO code uses US spelling "Organization".  Please be consistent with it (`getAdminOrganisations`)
* comments "If you are not an admin" ==> "If you are not a global admin"

I think the above would still be useful to future readers of the code - thanks for all the effort on this.

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, that's now nice and clean code!

And I appreciate the documentation of `AdminHelper.getInsiderGroups()`.

In the final review, I have found two very minor nits:
* `getInsiderGroups()` now calls `unique()` on the return value, so not needed to call it again in `GroupController.getFilteredList()`.  I'd expect an (implicit) contract for the getGroups/Orgs methods would be to return unique lists.
* typo: "gobal" => "global"

Feel free to merge this after you make the changes - no need for another round of review.

Thanks for patience and perseverance!

Cheers,
Vlad

PS: For the merge itself, wondering whether to preserve all the 20+ commits in this case, or do a "squash merge" (unfolds under the Merge button).  Leaving that up to you.

**Comment by Razorfang** [comment]
@vladimir-mencl-eresearch  My personal preference is to squash commits unless we might need to look up or cherry-pick specific commits later. Because a lot of these commits are just working towards a single update, I would personally squash them. Does REANNZ have a policy that thinks differently?

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the final changes - all good to merge now.

I think you grasped the sequence of commits here well as "just working towards a single update".

Agree to Squash in this case.  Can talk more tomorrow.

**Pull request merged**
